name: advertising
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  http: ^1.5.0
  flutter_dotenv: ^5.2.1
  image_picker: ^1.2.0
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  google_fonts: ^6.3.0
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  path_provider: ^2.1.5
  share_plus: ^11.1.0
  intl: ^0.20.2
  permission_handler: ^12.0.1
  flutter_staggered_animations: ^1.1.1
  youtube_player_flutter: ^9.1.2
  audio_service: ^0.18.18
  audio_session: ^0.2.2
  no_screenshot: ^0.3.1
  carousel_slider: ^5.1.1
  url_launcher: ^6.3.2
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

  
  assets:
  - .env

